apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-reservation-app
  namespace: flight-reservation
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: flight-reservation-app
  template:
    metadata:
      labels:
        app: flight-reservation-app
    spec:
      containers:
        - name: flight-reservation-app
          image: anuragpatilcloud/flight-reservation-app:6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mariadb:3306/flight-reservation-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flight-reservation-secrets
                  key: DB_ROOT_PASSWORD
            - name: FRONTEND_URL
              value: http://localhost
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
